name: Go

on:
  workflow_dispatch:
    inputs:
      update_dedicated_image:
        description: ""
        type: boolean
        default: false
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      PRE_DEF_VERSION: ${{ inputs.update_dedicated_image && 'v8.5.0' || 'v7.1.0' }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make

    - name: Test
      run: make test
